<?php
/** @package Sistema::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("autoridadeMap.php");

/**
 * autoridadeDAO provides object-oriented access to the authority table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Sistema::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class autoridadeDAO extends Phreezable
{
	/** @var int */
	public $Idauthority;

	/** @var string */
	public $Name;

	/** @var bit */
	public $Audisplay;

	/** @var bit */
	public $Aulist;

	/** @var bit */
	public $Auinsert;

	/** @var bit */
	public $Auupdate;

	/** @var bit */
	public $Auread;

	/** @var bit */
	public $Audelete;

	/** @var bit */
	public $Auexecute;

	/** @var bit */
	public $Auexport;

	/** @var int */
	public $Module;

	/** @var int */
	public $Institution;



}
?>