<?php
/** @package Sistema::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("contatoMap.php");

/**
 * contatoDAO provides object-oriented access to the contact table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Sistema::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class contatoDAO extends Phreezable
{
	/** @var int */
	public $Idcontact;

	/** @var int */
	public $Institution;

	/** @var int */
	public $Iditem;

	/** @var int */
	public $Idexposition;

	/** @var int */
	public $Idholder;

	/** @var int */
	public $Idcreator;

	/** @var int */
	public $User;

	/** @var string */
	public $Contactname;

	/** @var string */
	public $Urla;

	/** @var string */
	public $Contactcall;

	/** @var string */
	public $Company;

	/** @var string */
	public $Uri;

	/** @var string */
	public $Identity;

	/** @var string */
	public $Federaltaxcode;

	/** @var string */
	public $Statetaxcode;

	/** @var string */
	public $Countytaxcode;



}
?>