<?php
/** @package Sistema::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("criador_itemMap.php");

/**
 * criador_itemDAO provides object-oriented access to the itemcreator table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Sistema::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class criador_itemDAO extends Phreezable
{
	/** @var int */
	public $Iditemcreator;

	/** @var int */
	public $Item;

	/** @var int */
	public $Creator;

	/** @var string */
	public $Type;

	/** @var string */
	public $Location;

	/** @var bit */
	public $Attributed;


	/**
	 * Returns the foreign object based on the value of Creator
	 * @return Creator
	 */
	public function GetCreator()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_document_has_creator_creator1");
	}

	/**
	 * Returns the foreign object based on the value of Item
	 * @return Item
	 */
	public function GetItem()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_document_has_creator_document1");
	}


}
?>