<?php
/** @package Sistema::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("descricao_fisicaMap.php");

/**
 * descricao_fisicaDAO provides object-oriented access to the physicaldescription table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Sistema::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class descricao_fisicaDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var int */
	public $Item;

	/** @var string */
	public $Apexiso;

	/** @var string */
	public $Arabicpagenumbering;

	/** @var string */
	public $Asaiso;

	/** @var string */
	public $Boundtype;

	/** @var string */
	public $Color;

	/** @var string */
	public $Colorsystem;

	/** @var string */
	public $Columnnumber;

	/** @var string */
	public $Compressionmethod;

	/** @var string */
	public $Contentcolor;

	/** @var string */
	public $Contentextent;

	/** @var string */
	public $Contentfinishing;

	/** @var string */
	public $Contentsubstract;

	/** @var string */
	public $Contenttype;

	/** @var string */
	public $Covercolor;

	/** @var string */
	public $Coverfinishing;

	/** @var string */
	public $Coversubstract;

	/** @var string */
	public $Defaultapplication;

	/** @var string */
	public $Dustjacketcolor;

	/** @var string */
	public $Dustjacketfinishing;

	/** @var string */
	public $Dustjacketsubstract;

	/** @var string */
	public $Endpaper;

	/** @var string */
	public $Exif;

	/** @var string */
	public $Format;

	/** @var string */
	public $Framerate;

	/** @var string */
	public $Hasdustjacket;

	/** @var string */
	public $Hassound;

	/** @var string */
	public $Hasspecialfold;

	/** @var string */
	public $Iscompressed;

	/** @var string */
	public $Lengthtxt;

	/** @var string */
	public $Master;

	/** @var string */
	public $Media;

	/** @var string */
	public $Mediasupport;

	/** @var string */
	public $Movements;

	/** @var string */
	public $Other;

	/** @var string */
	public $Projectionmode;

	/** @var string */
	public $Romanpage;

	/** @var string */
	public $Sizetxt;

	/** @var string */
	public $Soundsystem;

	/** @var string */
	public $Specialfold;

	/** @var string */
	public $Specialpagenumebring;

	/** @var string */
	public $Technique;

	/** @var string */
	public $Timecode;

	/** @var string */
	public $Tinting;

	/** @var string */
	public $Titlepage;

	/** @var string */
	public $Totaltime;

	/** @var string */
	public $Type;

	/** @var string */
	public $Writingformat;


	/**
	 * Returns the foreign object based on the value of Item
	 * @return Item
	 */
	public function GetItem()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_item_physical");
	}


}
?>