<?php
/** @package Sistema::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("dimensao_itemMap.php");

/**
 * dimensao_itemDAO provides object-oriented access to the itemdimension table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Sistema::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class dimensao_itemDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var int */
	public $Item;

	/** @var string */
	public $Dimensiontype;

	/** @var string */
	public $Dimensionunit;

	/** @var string */
	public $Dimensionvalue;


	/**
	 * Returns the foreign object based on the value of Item
	 * @return Item
	 */
	public function GetItem()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_item_dimension");
	}


}
?>