<?php
/** @package Sistema::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("dimensaoMap.php");

/**
 * dimensaoDAO provides object-oriented access to the dimension table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Sistema::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class dimensaoDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Unit;

	/** @var string */
	public $Value;


	/**
	 * Returns a dataset of ExpositionDimension objects with matching Dimension
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetExpositionDimensions($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "FK_69we0kulo49s1sr97htshsxtw", $criteria);
	}


}
?>