<?php
/** @package Sistema::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("estadoMap.php");

/**
 * estadoDAO provides object-oriented access to the state table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Sistema::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class estadoDAO extends Phreezable
{
	/** @var int */
	public $Idstate;

	/** @var int */
	public $Country;

	/** @var string */
	public $State;

	/** @var string */
	public $Statecode;


	/**
	 * Returns a dataset of City objects with matching State
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetCitys($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_city_state1", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of Country
	 * @return Country
	 */
	public function GetCountry()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_state_country1");
	}


}
?>