<?php
/** @package Sistema::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("expoisicaoMap.php");

/**
 * expoisicaoDAO provides object-oriented access to the exposition table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Sistema::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class expoisicaoDAO extends Phreezable
{
	/** @var int */
	public $Idexposition;

	/** @var int */
	public $Institution;

	/** @var string */
	public $Location;

	/** @var string */
	public $Curator;

	/** @var string */
	public $Initialdate;

	/** @var string */
	public $Enddate;

	/** @var string */
	public $Description;

	/** @var string */
	public $Notes;

	/** @var string */
	public $Name;

	/** @var string */
	public $Exposubtype;

	/** @var string */
	public $Expotype;

	/** @var bit */
	public $Iscarriedbyotherinstitution;

	/** @var bit */
	public $Isinternational;

	/** @var string */
	public $Otherinfo;


	/**
	 * Returns a dataset of Expoitem objects with matching Exposition
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetExpoitems($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_expoitem_exposition", $criteria);
	}

	/**
	 * Returns a dataset of ExpositionCreator objects with matching Exposition
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetExpositionCreators($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "FK_kwh7ariugb0qjrwhpo3rai1uy", $criteria);
	}

	/**
	 * Returns a dataset of ExpositionDimension objects with matching Exposition
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetExpositionDimensions($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "FK_ai09pidrxa780uxmakwlex92c", $criteria);
	}

	/**
	 * Returns a dataset of ExpositionHistory objects with matching Idexposition
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetIdExpositionHistorys($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "FK_g6g5n45iyajyahsp1dfaeff4b", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of Institution
	 * @return Institution
	 */
	public function GetInstitution()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_exposition_institution1");
	}


}
?>