<?php
/** @package Sistema::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("expo_itemMap.php");

/**
 * expo_itemDAO provides object-oriented access to the expoitem table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Sistema::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class expo_itemDAO extends Phreezable
{
	/** @var int */
	public $Idexpoitem;

	/** @var int */
	public $Item;

	/** @var int */
	public $Exposition;

	/** @var string */
	public $Type;


	/**
	 * Returns the foreign object based on the value of Exposition
	 * @return Exposition
	 */
	public function GetExposition()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_expoitem_exposition");
	}

	/**
	 * Returns the foreign object based on the value of Item
	 * @return Item
	 */
	public function GetItem()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_expoitem_item");
	}


}
?>