<?php
/** @package Sistema::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("fundoMap.php");

/**
 * fundoDAO provides object-oriented access to the fond table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Sistema::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class fundoDAO extends Phreezable
{
	/** @var int */
	public $Idfond;

	/** @var int */
	public $Institution;

	/** @var string */
	public $Fond;

	/** @var string */
	public $Description;

	/** @var string */
	public $Otherinformation;

	/** @var int */
	public $Countitem;

	/** @var string */
	public $Type;


	/**
	 * Returns a dataset of Level objects with matching Fond
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetLevels($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_serie_fond1", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of Institution
	 * @return Institution
	 */
	public function GetInstitution()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_fond_institution1");
	}


}
?>