<?php
/** @package Sistema::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("historicoMap.php");

/**
 * historicoDAO provides object-oriented access to the history table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Sistema::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class historicoDAO extends Phreezable
{
	/** @var int */
	public $Idhistory;

	/** @var string */
	public $Type;

	/** @var string */
	public $Description;

	/** @var string */
	public $Date;

	/** @var string */
	public $Actor;

	/** @var int */
	public $Item;

	/** @var int */
	public $Institution;

	/** @var int */
	public $Idexposition;

	/** @var float */
	public $Cost;

	/** @var int */
	public $Creator;

	/** @var bit */
	public $Ispublic;


	/**
	 * Returns the foreign object based on the value of Institution
	 * @return Institution
	 */
	public function GetInstitution()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_history_institution1");
	}

	/**
	 * Returns the foreign object based on the value of Item
	 * @return Item
	 */
	public function GetItem()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_history_item1");
	}


}
?>