<?php
/** @package Sistema::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("itemMap.php");

/**
 * itemDAO provides object-oriented access to the item table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Sistema::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class itemDAO extends Phreezable
{
	/** @var int */
	public $Iditem;

	/** @var int */
	public $Holder;

	/** @var int */
	public $Level;

	/** @var int */
	public $Institution;

	/** @var string */
	public $Inventoryid;

	/** @var string */
	public $Uritype;

	/** @var string */
	public $Uri;

	/** @var string */
	public $Keywords;

	/** @var string */
	public $Description;

	/** @var string */
	public $Uidtype;

	/** @var string */
	public $Uid;

	/** @var string */
	public $Class;

	/** @var string */
	public $Type;

	/** @var bit */
	public $Iseletronic;

	/** @var string */
	public $Creationdate;

	/** @var string */
	public $Acquisitiondate;

	/** @var string */
	public $Scopecontent;

	/** @var bit */
	public $Originalexistence;

	/** @var string */
	public $Originallocation;

	/** @var string */
	public $Repositorycode;

	/** @var bit */
	public $Copyexistence;

	/** @var string */
	public $Copylocation;

	/** @var string */
	public $Legalaccess;

	/** @var string */
	public $Accesscondition;

	/** @var string */
	public $Reproductionrights;

	/** @var string */
	public $Reproductionrightsdescription;

	/** @var string */
	public $Itemdate;

	/** @var string */
	public $Publishdate;

	/** @var string */
	public $Publisher;

	/** @var string */
	public $Itematributes;

	/** @var bit */
	public $Ispublic;

	/** @var string */
	public $Preliminaryrule;

	/** @var string */
	public $Punctuation;

	/** @var string */
	public $Notes;

	/** @var string */
	public $Otherinformation;

	/** @var string */
	public $Titledefault;

	/** @var int */
	public $Subitem;

	/** @var bit */
	public $Deletecomfirm;

	/** @var int */
	public $Typeitem;

	/** @var string */
	public $Edition;

	/** @var bit */
	public $Isexposed;

	/** @var bit */
	public $Isoriginal;

	/** @var bit */
	public $Ispart;

	/** @var bit */
	public $Haspart;

	/** @var string */
	public $Ispartof;

	/** @var int */
	public $Numberofcopies;

	/** @var date */
	public $Tobepublicin;

	/** @var bit */
	public $Creationdateattributed;

	/** @var bit */
	public $Itemdateattributed;

	/** @var bit */
	public $Publishdateattributed;

	/** @var string */
	public $Serachdump;

	/** @var string */
	public $Itemmediadir;


	/**
	 * Returns a dataset of Documentation objects with matching Item
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetDocumentations($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_document_item1", $criteria);
	}

	/**
	 * Returns a dataset of Expoitem objects with matching Item
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetExpoitems($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_expoitem_item", $criteria);
	}

	/**
	 * Returns a dataset of History objects with matching Item
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetHistorys($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_history_item1", $criteria);
	}

	/**
	 * Returns a dataset of ItemMedia objects with matching ItemIditem
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetItemMedias($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "FK_4922opf11ju2cvt7s73ofcb8a", $criteria);
	}

	/**
	 * Returns a dataset of Itemcreator objects with matching Item
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetItemcreators($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_document_has_creator_document1", $criteria);
	}

	/**
	 * Returns a dataset of Itemdescription objects with matching Item
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetItemdescriptions($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_item_description", $criteria);
	}

	/**
	 * Returns a dataset of Itemdimension objects with matching Item
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetItemdimensions($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_item_dimension", $criteria);
	}

	/**
	 * Returns a dataset of Iteminscription objects with matching Tem
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetTemIteminscriptions($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_item_inscription", $criteria);
	}

	/**
	 * Returns a dataset of Media objects with matching Item
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetMedias($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_media_item1", $criteria);
	}

	/**
	 * Returns a dataset of Physicaldescription objects with matching Item
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetPhysicaldescriptions($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_item_physical", $criteria);
	}

	/**
	 * Returns a dataset of RelationshipItem objects with matching Item
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetRelationshipItems($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "FK_c0y3gf5cowm6uo7ecld19tuqa", $criteria);
	}

	/**
	 * Returns a dataset of RelationshipItem objects with matching Relationship
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetRelationshipRelationshipItems($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "FK_geqqk61hbyqn45ylpg1fwctja", $criteria);
	}

	/**
	 * Returns a dataset of Title objects with matching Item
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetTitles($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_title_item1", $criteria);
	}

	/**
	 * Returns a dataset of Transcription objects with matching Iditem
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetIdTranscriptions($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_transcription_item1", $criteria);
	}


}
?>