<?php
/** @package Sistema::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("localMap.php");

/**
 * localDAO provides object-oriented access to the place_location table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Sistema::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class localDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Complement;

	/** @var string */
	public $Latituded;

	/** @var string */
	public $Local;

	/** @var string */
	public $Longitude;

	/** @var string */
	public $Number;

	/** @var string */
	public $Otherinformation;

	/** @var string */
	public $Street;

	/** @var string */
	public $Type;

	/** @var string */
	public $Zipcode;

	/** @var int */
	public $City;

	/** @var int */
	public $Country;

	/** @var int */
	public $Institution;

	/** @var int */
	public $State;



}
?>