<?php
/** @package Sistema::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("midia_armazanenamentoMap.php");

/**
 * midia_armazanenamentoDAO provides object-oriented access to the storage_media table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Sistema::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class midia_armazanenamentoDAO extends Phreezable
{
	/** @var int */
	public $StorageIdstorage;

	/** @var int */
	public $MediasIdmedia;


	/**
	 * Returns the foreign object based on the value of StorageIdstorage
	 * @return Storage
	 */
	public function GetStorage()
	{
		return $this->_phreezer->GetManyToOne($this, "FK_hrmsbocvkwn14rnyh8qj55dfc");
	}

	/**
	 * Returns the foreign object based on the value of MediasIdmedia
	 * @return Media
	 */
	public function GetSMedia()
	{
		return $this->_phreezer->GetManyToOne($this, "FK_nmymba781jas5ih7fojmm9435");
	}


}
?>