<?php
/** @package Sistema::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("n_contatoMap.php");

/**
 * n_contatoDAO provides object-oriented access to the ncontact table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Sistema::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class n_contatoDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Call_;

	/** @var string */
	public $Company;

	/** @var string */
	public $CountyTaxcode;

	/** @var string */
	public $FederalTaxcode;

	/** @var string */
	public $Identity;

	/** @var string */
	public $Name;

	/** @var string */
	public $StateTaxcode;

	/** @var string */
	public $Uri;

	/** @var string */
	public $Urla;

	/** @var int */
	public $Institution;


	/**
	 * Returns the foreign object based on the value of Institution
	 * @return Institution
	 */
	public function GetInstitution()
	{
		return $this->_phreezer->GetManyToOne($this, "FK_q27ejta8y2arisfx6k2v8y01v");
	}


}
?>