<?php
/** @package Sistema::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("n_referenciaMap.php");

/**
 * n_referenciaDAO provides object-oriented access to the nreference table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Sistema::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class n_referenciaDAO extends Phreezable
{
	/** @var int */
	public $Id;

	/** @var string */
	public $Author;

	/** @var string */
	public $Description;

	/** @var string */
	public $OtherInformation;

	/** @var string */
	public $Text;

	/** @var string */
	public $Title;

	/** @var int */
	public $Institution;


	/**
	 * Returns the foreign object based on the value of Institution
	 * @return Institution
	 */
	public function GetInstitution()
	{
		return $this->_phreezer->GetManyToOne($this, "FK_360fxrl1q9vf3b3yu70b0lxl1");
	}


}
?>