<?php
/** @package Sistema::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("nivel_instituicoesMap.php");

/**
 * nivel_instituicoesDAO provides object-oriented access to the institution_level table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Sistema::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class nivel_instituicoesDAO extends Phreezable
{
	/** @var int */
	public $InstitutionIdinstitution;

	/** @var int */
	public $LevelsIdlevel;


	/**
	 * Returns the foreign object based on the value of InstitutionIdinstitution
	 * @return Institution
	 */
	public function GetInstitution()
	{
		return $this->_phreezer->GetManyToOne($this, "FK_4pu1mko6s7rh12iydqohhngj");
	}

	/**
	 * Returns the foreign object based on the value of LevelsIdlevel
	 * @return Level
	 */
	public function GetSLevel()
	{
		return $this->_phreezer->GetManyToOne($this, "FK_56md01pp54ivtjhs8gg0esb9s");
	}


}
?>