<?php
/** @package Sistema::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("nivel_fundoMap.php");

/**
 * nivel_fundoDAO provides object-oriented access to the fond_level table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Sistema::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class nivel_fundoDAO extends Phreezable
{
	/** @var int */
	public $FondIdfond;

	/** @var int */
	public $LevelsIdlevel;



}
?>