<?php
/** @package Sistema::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("papel_usuarioMap.php");

/**
 * papel_usuarioDAO provides object-oriented access to the userrole table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Sistema::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class papel_usuarioDAO extends Phreezable
{
	/** @var int */
	public $Iduserrole;

	/** @var int */
	public $User;

	/** @var int */
	public $Role;


	/**
	 * Returns the foreign object based on the value of Role
	 * @return Role
	 */
	public function GetRole()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_user_has_role_role1");
	}

	/**
	 * Returns the foreign object based on the value of User
	 * @return User
	 */
	public function GetUser()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_user_has_role_user1");
	}


}
?>