<?php
/** @package Sistema::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("papelMap.php");

/**
 * papelDAO provides object-oriented access to the role table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Sistema::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class papelDAO extends Phreezable
{
	/** @var int */
	public $Idrole;

	/** @var string */
	public $Name;

	/** @var int */
	public $Institution;


	/**
	 * Returns a dataset of Userrole objects with matching Role
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetUserroles($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_user_has_role_role1", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of Institution
	 * @return Institution
	 */
	public function GetInstitution()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_role_institution1");
	}


}
?>