<?php
/** @package Sistema::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("referenciaMap.php");

/**
 * referenciaDAO provides object-oriented access to the reference table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Sistema::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class referenciaDAO extends Phreezable
{
	/** @var int */
	public $Idreference;

	/** @var int */
	public $Item;

	/** @var int */
	public $Institution;

	/** @var int */
	public $Creator;

	/** @var string */
	public $Referencetype;

	/** @var string */
	public $Referencetitle;

	/** @var string */
	public $Referencedescription;

	/** @var string */
	public $Referenceauthor;

	/** @var string */
	public $Referencetext;

	/** @var string */
	public $Otherinformations;


	/**
	 * Returns the foreign object based on the value of Institution
	 * @return Institution
	 */
	public function GetInstitution()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_reference_institution1");
	}


}
?>