<?php
/** @package Sistema::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("timezoneMap.php");

/**
 * timezoneDAO provides object-oriented access to the timezones table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Sistema::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class timezoneDAO extends Phreezable
{
	/** @var int */
	public $Idtimezone;

	/** @var string */
	public $Name;


	/**
	 * Returns a dataset of Institution objects with matching Timezone
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetTimezoneInstitutions($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_institution_timezone", $criteria);
	}

	/**
	 * Returns a dataset of User objects with matching Timezone
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetTimezoneUsers($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_user_timezone", $criteria);
	}


}
?>