<?php
/** @package Sistema::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("usuarioMap.php");

/**
 * usuarioDAO provides object-oriented access to the user table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Sistema::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class usuarioDAO extends Phreezable
{
	/** @var int */
	public $Iduser;

	/** @var int */
	public $Institution;

	/** @var string */
	public $Fullname;

	/** @var string */
	public $Username;

	/** @var string */
	public $Password;

	/** @var string */
	public $Notes;

	/** @var string */
	public $Code;

	/** @var int */
	public $Timezone;

	/** @var timestamp */
	public $Lastlogin;

	/** @var int */
	public $Status;

	/** @var bit */
	public $Admin;


	/**
	 * Returns a dataset of Search objects with matching User
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetSearchs($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_search_user1", $criteria);
	}

	/**
	 * Returns a dataset of Userrole objects with matching User
	 * @param Criteria
	 * @return DataSet
	 */
	public function GetUserroles($criteria = null)
	{
		return $this->_phreezer->GetOneToMany($this, "fk_user_has_role_user1", $criteria);
	}

	/**
	 * Returns the foreign object based on the value of Institution
	 * @return Institution
	 */
	public function GetInstitution()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_user_institution1");
	}

	/**
	 * Returns the foreign object based on the value of Timezone
	 * @return Timezones
	 */
	public function GetTimezoneTimezones()
	{
		return $this->_phreezer->GetManyToOne($this, "fk_user_timezone");
	}


}
?>